version: '2'
services:
  dev-nginx:
    container_name: dev_nginx
    image: dev-nginx/nginx
    restart: always
    build:
      context: .
      args:
        env: dev
    ports:
      - "443:443"
      - "80:80"
    networks:
      dev-default:
        aliases:
          - nginx.bat.dev
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /var/log/dev/nginx:/etc/nginx/logging
networks:
  dev-default:
    external: true